#define WW "/players/trout/weapons"
#define MM "/players/trout/mobs"
#define YY "/players/trout"
#define ZZ "/players/trout/area"
#define AAA "/players/trout/armours"
#define DD dest_dir
#define QNAME query_name
#define AA add_action
#define CO clone_object
#define MO move_object
#define TO this_object
#define RAN random
#define GM "guild/master"
#define GP add_money
#define IC init_command
#define TP this_player
#define HIT hit_player
#define TLR tell_room
#define ENV environment
#define TELL tell_object
#define CAP capitalize
#define CL clone_list=
#define QRN query_real_name
#define QLEVEL query_level
#define QLLEVEL query_legend_level
#define QSP query_sp()
#define QMSP query_maxsp()
#define RSP restore_spell_points

#define TPN TP()->QNAME()
#define TPRN TP()->QRN()
#define TPQL TP()->QLEVEL()
#define TPQLL TP()->QLLEVEL()
#define TPQSP TP()->QSP
#define TPQMSP TP()->QMSP
#define TPRSP TP()->RSP

#define BIN "/players/trout/psi/bin/"
#define PSI "/players/trout/psi"
