#define PATH "/players/sylvyn/area/rooms/amazon/"
#define SOUTH "south/"
#define NORTH "north/"
#define WEST "west/"
#define EAST "east/"
#define CENTRAL "central/"
#define NW "northwest/"
#define NE "northeast/"
#define SW "southwest/"
#define SE "southeast/"
#define TRIBE "villages/north/"
#define RIVER "/players/sylvyn/area/rooms/river/"
#define MONSTER "/players/sylvyn/area/monsters/amazon/"
#define VMON "/players/sylvyn/area/monsters/amazon/villages/"
#define OBJECT "/players/sylvyn/area/objects/amazon/"
#define MO move_object
#define CMV(x) move_object(clone_object(VMON+x),this_object())
#define CM(x) move_object(clone_object(MONSTER+x),this_object())
#define CO clone_object
#define TO this_object()
#define CLONER  "/players/nylakoorub/misc/functions/cloner.c"
