#define VERBS ({\
	({"admire", 	"admire"}),\
	({"apologize",  "apologize"}),\
	({"applaud", 	"applaud"}),\
	({"bang", 	"bang"}),\
	({"trite", 	"blush"}),\
	({"trite", 	"bounce"}),\
	({"bow", 	"bow"}),\
	({"trite", 	"burp"}),\
	({"trite", 	"cackle"}),\
	({"trite", 	"chuckle"}),\
	({"trite", 	"clap"}),\
	({"trite", 	"cheer"}),\
	({"comfort", 	"comfort"}),\
	({"complain", 	"complain"}),\
	({"trite", 	"cough"}),\
	({"trite", 	"cry"}),\
	({"cuddle", 	"cuddle"}),\
	({"curse", 	"curse"}),\
	({"curtsey", 	"curtsey"}),\
	({"dance", 	"dance"}),\
        ({"trite",	"die"}),\
	({"excuse",	"excuse"}),\
	({"fail", 	"fail"}),\
	({"trite", 	"fart"}),\
	({"fear", 	"fear"}),\
	({"finger", 	"finger"}),\
	({"trite", 	"flip"}),\
	({"fondle", 	"fondle"}),\
	({"french", 	"french"}),\
	({"tog_frog", 	"frog"}),\
	({"trite", 	"frown"}),\
	({"trite", 	"gasp"}),\
	({"trite", 	"giggle"}),\
	({"glare", 	"glare"}),\
	({"trite", 	"grin"}),\
	({"trite", 	"groan"}),\
	({"grope", 	"grope"}),\
	({"verb_adv_at_per", "growl"}),\
	({"trite", 	"hiccup"}),\
	({"hug", 	"hug"}),\
	({"ignore", 	"ignore"}),\
	({"kick", 	"kick"}),\
	({"kiss", 	"kiss"}),\
	({"knee", 	"knee"}),\
	({"trite", 	"laugh"}),\
	({"lick", 	"lick"}),\
	({"look", 	"look"}),\
	({"love", 	"love"}),\
	({"mercy", 	"mercy"}),\
	({"trite", 	"moan"}),\
	({"nibble", 	"nibble"}),\
	({"no", 	"no"}),\
	({"trite", 	"nod"}),\
	({"nose", 	"nose"}),\
	({"pale", 	"pale"}),\
	({"pat", 	"pat"}),\
	({"trite", 	"point"}),\
	({"poke", 	"poke"}),\
	({"trite", 	"pout"}),\
	({"puke", 	"puke"}),\
	({"praise", 	"praise"}),\
	({"trite", 	"protest"}),\
	({"trite", 	"purr"}),\
	({"puzzle", 	"puzzle"}),\
	({"relax", 	"relax"}),\
	({"roll",	"roll"}),\	
	({"ruffle", 	"ruffle"}),\
	({"scratch", 	"scratch"}),\
	({"trite", 	"scream"}),\
	({"shake", 	"shake"}),\
	({"shame", 	"shame"}),\
	({"shiver", 	"shiver"}),\
	({"trite", 	"shrug"}),\
	({"trite", 	"sigh"}),\
	({"sing", 	"sing"}),\
	({"slap", 	"slap"}),\
	({"trite", 	"smile"}),\
	({"verb_adv", 	"smirk"}),\
	({"snap", 	"snap"}),\
	({"trite", 	"sneeze"}),\
	({"verb_adv",  "snicker"}),\
	({"verb_adv", 	"sniff"}),\
	({"trite", 	"snore"}),\
	({"snuggle", 	"snuggle"}),\
	({"verb_adv", 	"sob"}),\
	({"spit", 	"spit"}),\
	({"squeeze", 	"squeeze"}),\
	({"stare", 	"stare"}),\
	({"trite", 	"strut"}),\
	({"sulk", 	"sulk"}),\
	({"sweat", 	"sweat"}),\
        ({"trite",	"tap"}),\
	({"thank", 	"thank"}),\
	({"throat", 	"throat"}),\
	({"tickle", 	"tickle"}),\
	({"tongue", 	"tongue"}),\
	({"twiddle", 	"twiddle"}),\
	({"trite", 	"wait"}),\
	({"wave", 	"wave"}),\
	({"trite", 	"whistle"}),\
	({"wiggle", 	"wiggle"}),\
	({"wink", 	"wink"}),\
	({"wipe", 	"wipe"}),\
	({"trite", 	"yawn"}) ,\
    })\
