#define MONST "/players/whisky/quest/monster/"
#define OBJ   "/players/whisky/quest/obj/"
#define PATH  "/players/whisky/quest/room/"
#define FORST "/players/whisky/quest/room/forest/"
#define E  environment
#define TP    this_player()
#define TPN   TP->query_name()
#define TPP   TP->query_possessive()
#define TPO   TP->query_objective()
#define TPH   TP->query_hit_point()
#define TPS   TP->query_spell_points()
#define TO    this_object()
#define TOI   TO->query_id()
#define MONK  "guild/master"->query_number()->("monk") 
#define MAGE  "guild/master"->query_number()->("mage")
#define THIEF "guild/master"->query_number()->("thief")
#define FIGHTER "guild/master"->query_number()->("fighter")
#define NMONK TP->query_guild()!=MONK
#define NMAGE TP->query_guild()!=MAGE
#define NTHIEF TP->query_guild()!=THIEF
#define NFIGHTER TP->query_guild()!=FIGHTER
#define TPST TP->query_str()
