#0:0
name_of_friend "muzmuz"
current_path "players/oink"
domains 0
xperms 0
ftp_user 0
name "oink"
race 0
level 5
size 0
weight 10
money 0
hit_point 1870
spell_points 103
fatigue_points 16
max_hp 420
max_sp 850
max_fp 200
experience 12347
age 2362
alignment 103
gender 1
guild 2
stats ({40,40,40,40,40,40,})
skills 0
spells ({({}),({}),({}),({}),})
languages ({100,0,0,})
nskills 0
time_to_heal 4
msgin "arrives"
msgout "leaves"
mmsgout "disappears in a puff of smoke"
mmsgin "arrives in a puff of smoke"
my_smell 0
real_race "hobbit"
real_size 2
whimpy 0
is_npc 0
brief 0
is_wizard 0
ghost 0
is_invis 0
frog 0
no_fight 0
dead 0
spend_points 0
auto_load "players/moonchild/misc/addendum:^!"
flags 0
props 0
abilities ({({}),({}),({}),({}),})
alias_list ({({"k","2","1","3","h","v",}),({"kill tourist","sneak west","hide","backstab wuntvor","heal","score",}),})
nick_list ({({}),({}),})
sep ";"
env_var (["SHORT":"Oink the Hobbit",])
quests ([])
pretitle ""
title "Picker"
al_title "evil"
real_al_title "evil"
is_linkdead 0
intoxicated 0
stuffed 0
soaked 0
poisoned 0
is_resting 0
headache 0
max_headache 0
user_status 0
called_from_ip "140.78.40.25"
needed_quests 0
start_where 0
tot_value 0
stats_is_updated 1
description 0
prompt ({0,0,0,0,0,0,0,1,})
bug_file_size 0
religion 0
explored 0
incognito 1
start_at_guild 0
is_pk 0
legend_level 0
practice_sess 0
last_practice_level 0
call 0
autoloot 0
other_copy 0
scar 258
