/* Common defines */

#define TP this_player()
#define E(x) environment(x)
#define QN query_name()
#define QRN query_real_name()
#define TO this_object()
#define ETO environment(TO)
#define ETP environment(TP)
#define QPO query_possessive()
#define QOB query_objective()
#define CTPRN capitalize(TP->QRN)
#define CTPN capitalize(TP->QN)
#define CP(x) capitalize(x)
#define SP query_sp()
#define HP query_hp()
