({

  ({ ({0,0,0}),({"the Apprentice Wizard","the Apprentice Wizard",
                 "the Apprentice Wizard"}) }),
  ({ ({0,0,0}),({"the Harper","the Harper","the Harper"}) }),
  ({ ({0,0,0}),({"the Apprentice Harper","the Apprentice Harper",
                 "the Apprentice Harper"}) }),
  ({ ({0,0,0}),({"the Wallcrumbler","the Wallcrumbler",
                 "the Wallcrumbler"}) }),
  ({ ({0,0,0}),({"the Soundmaster","the Soundmistress",
                 "the Soundmaster"}) }),
  ({ ({0,0,0}),({"the Shatterer","the Shatterer","the Shatterer"}) }),	
  ({ ({0,0,0}),({"the Panicbringer","the Panicbringer",
                 "the Panicbringer"}) }),
  ({ ({0,0,0}),({"the Knowledgable","the Knowledgable",
                 "the Knowledgable"}) }),
  ({ ({0,0,0}),({"the Mindclearer","the Mindclearer","the Mindclearer"}) }),
  ({ ({0,0,0}),({"the Original","the Original","the Original"}) }),
  ({ ({0,0,0}),({"the Crackcaller","the Crackcaller","the Crackcaller"}) }),	
  ({ ({0,0,0}),({"the Loremaster","the Loremistress","the Loremaster"}) }),
  ({ ({0,0,0}),({"the Fearbringer","the Fearbringer","the Fearbringer"}) }),
  ({ ({0,0,0}),({"the Significant","the Significant","the Significant"}) }),	
  ({ ({0,0,0}),({"the Charmer","the Houri","the Charmer"}) }),
  ({ ({0,0,0}),({"the Sleepbringer","the Sleepbringer",
                 "the Sleepbringer"}) }),	
  ({ ({0,0,0}),({"the Analyst","the Analyst","the Analyst"}) }),
  ({ ({0,0,0}),({"the Mentalist","the Mentalist","the Mentalist"}) }),
  ({ ({0,0,0}),({"the Detective","the Detective","the Detective"}) }),		
  ({ ({0,0,0}),({"the Singer","the female Singer","the Singer"}) }),
  ({ ({0,0,0}),({"the Stunner","the Stunner","the Stunner"}) }),		
  ({ ({0,0,0}),({"the Linguist","the Linguist","the Linguist"}) }),
  ({ ({0,0,0}),({"the Sounder","the Sounder","the Sounder"}) }),
  ({ ({0,0,0}),({"the Bass","the Soprano","the Bass"}) }),
  ({ ({0,0,0}),({"the Learner","the Learner","the Learner"}) }),
  ({ ({0,0,0}),({"the Appraiser","the Appraiser","the Appraiser"}) }),	
  ({ ({0,0,0}),({"the Whisperer","the Whisperer","the Whisperer"}) }),
  ({ ({0,0,0}),({"the Silent","the Silent","the Silent"}) }),
  ({ ({0,0,0}),({"the Soother","the Soother","the Soother"}) }),
  ({ ({0,0,0}),({"the Student","the girl Student","the Student"}) })
  });
