#define NOTHING 0
#define TWOKIND 100
#define TWOPAIR 200
#define THREEKIND 300
#define STRAIGHT 1000
#define FLUSH 2000
#define FULLHOUSE 4000
#define FOURKIND 5000
#define STRFLUSH 10000
#define ROYALFLUSH 20000
#define MAX_TIME 60
#define FILENAME "poker"
#define PATH "/players/haplo/casino"
#define SHUFFLECNT 4
#define NUM_CARDS 5
#define TRUE 1
#define FALSE 0
#define HEARTS 0
#define DIAMONDS 1
#define CLUBS 3
#define TWO 0
#define THREE 1
#define FOUR 2
#define FIVE 3
#define SIX 4
#define SEVEN 5
#define EIGHT 6
#define NINE 7
#define TEN 8
#define JACK 9
#define QUEEN 10
#define KING 11
#define ACE 12
#define SUIT 0
#define CARD 1
#define SPADES 2
