string bigword(string str) {
 string line1, line2, line3, line4, line5, line6, line7, line8;
 int i;

 line1 = "";
 line2 = "";
 line3 = "";
 line4 = "";
 line5 = "";
 line6 = "";
 line7 = "";
 line8 = "";

 for (i=0; i<strlen(str); i++) {
   switch (str[i]) {
     case ' ': line1 += "   ";
               line2 += "   ";
               line3 += "   ";
               line4 += "   ";
               line5 += "   ";
               line6 += "   ";
               line7 += "   ";
               line8 += "   ";
               break;
     case '!': line1 += " _ ";
               line2 += "( )";
               line3 += "| |";
               line4 += "| |";
               line5 += "| |";
               line6 += "(_)";
               line7 += "(_)";
               line8 += "   ";
               break;
     case '"': line1 += "  _  _  ";
               line2 += " ( )( ) ";
               line3 += " (_)(_) ";
               line4 += "        ";
               line5 += "        ";
               line6 += "        ";
               line7 += "        ";
               line8 += "        ";
               break;
     case '#': line1 += "          ";
               line2 += "   _  _   ";
               line3 += " _( )( )_ ";
               line4 += "(_  ..  _)";
               line5 += "(_      _)";
               line6 += "  (_)(_)  ";
               line7 += "          ";
               line8 += "          ";
               break;
     case '$': line1 += "  ( )  ";
               line2 += " /'_ \\ ";
               line3 += "( (_(_)";
               line4 += " \\__ \\ ";
               line5 += "( )_) )";
               line6 += "`\\_ _/'";
               line7 += "  (_)  ";
               line8 += "       ";
               break;
     case '%': line1 += " _       _ ";
               line2 += "(_)    /' )";
               line3 += "     /' /' ";
               line4 += "   /' /'   ";
               line5 += " /' /'   _ ";
               line6 += "(_/'    (_)";
               line7 += "           ";
               line8 += "           ";
               break;
     case '&': line1 += " _____   ";
               line2 += "(  _  )  ";
               line3 += "`\\  ,/'  ";
               line4 += " /'_`\\/\\ ";
               line5 += "| (_> ,<`";
               line6 += "`\\___/\\/'";
               line7 += "         ";
               line8 += "         ";
               break;
     case ''': line1 += " _ ";
               line2 += "( )";
               line3 += "|/ ";
               line4 += "   ";
               line5 += "   ";
               line6 += "   ";
               line7 += "   ";
               line8 += "   ";
               break;
     case '(': line1 += "   _ ";
               line2 += " /' )";
               line3 += "| ,/'";
               line4 += "| |  ";
               line5 += "| `\\ ";
               line6 += "`\\__)";
               line7 += "     ";
               line8 += "     ";
               break;
     case ')': line1 += " _   ";
               line2 += "( `\\ ";
               line3 += "`\\  |";
               line4 += "  | |";
               line5 += " /' |";
               line6 += "(__/'";
               line7 += "     ";
               line8 += "     ";
               break;
     case '*': line1 += "   _   ";
               line2 += " _( )_ ";
               line3 += "( ` ' )";
               line4 += " >   < ";
               line5 += "(_, ,_)";
               line6 += "  (_)  ";
               line7 += "       ";
               line8 += "       ";
               break;
     case '+': line1 += "    _    ";
               line2 += "   ( )   ";
               line3 += " __| |__ ";
               line4 += "(__   __)";
               line5 += "   | |   ";
               line6 += "   (_)   ";
               line7 += "         ";
               line8 += "         ";
               break;
     case ',': line1 += "   ";
               line2 += "   ";
               line3 += "   ";
               line4 += "   ";
               line5 += " _ ";
               line6 += "( )";
               line7 += "|/ ";
               line8 += "   ";
               break;
     case '-': line1 += "        ";
               line2 += "        ";
               line3 += " ______ ";
               line4 += "(______)";
               line5 += "        ";
               line6 += "        ";
               line7 += "        ";
               line8 += "        ";
               break;
     case '.': line1 += "   ";
               line2 += "   ";
               line3 += "   ";
               line4 += "   ";
               line5 += " _ ";
               line6 += "(_)";
               line7 += "   ";
               line8 += "   ";
               break;
     case '/': line1 += "        __ ";
               line2 += "       /  )";
               line3 += "     /' /' ";
               line4 += "   /' /'   ";
               line5 += " /' /'     ";
               line6 += "(_/'       ";
               line7 += "           ";
               line8 += "           ";
               break;
     case '0': line1 += "  __   ";
               line2 += "/' _`\\ ";
               line3 += "| ( ) |";
               line4 += "| | | |";
               line5 += "| (_) |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case '1': line1 += "   _ ";
               line2 += " /' )";
               line3 += "(_, |";
               line4 += "  | |";
               line5 += "  | |";
               line6 += "  (_)";
               line7 += "     ";
               line8 += "     ";
               break;
     case '2': line1 += "   __   ";
               line2 += " /'__`\\ ";
               line3 += "(_)  ) )";
               line4 += "   /' / ";
               line5 += " /' /( )";
               line6 += "(_____/'";
               line7 += "        ";
               line8 += "        ";
               break;
     case '3': line1 += "   ___ ";
               line2 += " /'_  )";
               line3 += "(_)_) |";
               line4 += " _(_ < ";
               line5 += "( )_) |";
               line6 += "`\\____)";
               line7 += "       ";
               line8 += "       ";
               break;
     case '4': line1 += " _  _   ";
               line2 += "( )( )  ";
               line3 += "| || |  ";
               line4 += "| || |_ ";
               line5 += "(__ ,__)";
               line6 += "   (_)  ";
               line7 += "        ";
               line8 += "        ";
               break;
     case '5': line1 += " _____ ";
               line2 += "(  ___)";
               line3 += "| (__  ";
               line4 += "|___ `\\";
               line5 += "( )_) |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case '6': line1 += " _____ ";
               line2 += "(  ___)";
               line3 += "| (__  ";
               line4 += "|  _ `\\";
               line5 += "| (_) |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case '7': line1 += " _______ ";
               line2 += "(_____  )";
               line3 += "     /'/'";
               line4 += "   /'/'  ";
               line5 += " /'/'    ";
               line6 += "(_/      ";
               line7 += "         ";
               line8 += "         ";
               break;
     case '8': line1 += "   _   ";
               line2 += " /'_`\\ ";
               line3 += "( (_) )";
               line4 += " > _ <'";
               line5 += "( (_) )";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case '9': line1 += "   __  ";
               line2 += " /'_ `\\";
               line3 += "( (_) |";
               line4 += " \\__, |";
               line5 += "    | |";
               line6 += "    (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case ':': line1 += "   ";
               line2 += "   ";
               line3 += " _ ";
               line4 += "(_)";
               line5 += " _ ";
               line6 += "(_)";
               line7 += "   ";
               line8 += "   ";
               break;
     case ';': line1 += "   ";
               line2 += "   ";
               line3 += " _ ";
               line4 += "(_)";
               line5 += " _ ";
               line6 += "( )";
               line7 += "|/ ";
               line8 += "   ";
               break;
     case '<': line1 += "     _ ";
               line2 += "   /' )";
               line3 += " /' /' ";
               line4 += "<  <   ";
               line5 += " \\  `\\ ";
               line6 += "  `\\__)";
               line7 += "       ";
               line8 += "       ";
               break;
     case '=': line1 += "        ";
               line2 += "        ";
               line3 += " ______ ";
               line4 += "(______)";
               line5 += "(______)";
               line6 += "        ";
               line7 += "        ";
               line8 += "        ";
               break;
     case '>': line1 += " _     ";
               line2 += "( `\\   ";
               line3 += " `\\ `\\ ";
               line4 += "   >  >";
               line5 += " /' /' ";
               line6 += "(_/'   ";
               line7 += "       ";
               line8 += "       ";
               break;
     case '?': line1 += "   _   ";
               line2 += " /'_`\\ ";
               line3 += "(_) ) |";
               line4 += "   /'/'";
               line5 += "  |_|  ";
               line6 += "  (_)  ";
               line7 += "       ";
               line8 += "       ";
               break;
     case '@': line1 += "          ";
               line2 += "     _    ";
               line3 += "   /'_`\\  ";
               line4 += " /'/'_` ) ";
               line5 += "( ( (_| | ";
               line6 += " \\ `\\__,_)";
               line7 += "  `\\_____)";
               line8 += "          ";
               break;
     case 'A': line1 += " _____ ";
               line2 += "(  _  )";
               line3 += "| (_) |";
               line4 += "|  _  |";
               line5 += "| | | |";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'B': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| (_) )";
               line4 += "|  _ <'";
               line5 += "| (_) )";
               line6 += "(____/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'C': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| ( (_)";
               line4 += "| |  _ ";
               line5 += "| (_( )";
               line6 += "(____/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'D': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| | ) |";
               line4 += "| | | )";
               line5 += "| |_) |";
               line6 += "(____/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'E': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| (_(_)";
               line4 += "|  _)_ ";
               line5 += "| (_( )";
               line6 += "(____/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'F': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| (_(_)";
               line4 += "|  _)  ";
               line5 += "| |    ";
               line6 += "(_)    ";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'G': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| ( (_)";
               line4 += "| |___ ";
               line5 += "| (_, )";
               line6 += "(____/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'H': line1 += " _   _ ";
               line2 += "( ) ( )";
               line3 += "| |_| |";
               line4 += "|  _  |";
               line5 += "| | | |";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'I': line1 += " _ ";
               line2 += "(_)";
               line3 += "| |";
               line4 += "| |";
               line5 += "| |";
               line6 += "(_)";
               line7 += "   ";
               line8 += "   ";
               break;
     case 'J': line1 += " _____ ";
               line2 += "(___  )";
               line3 += "    | |";
               line4 += " _  | |";
               line5 += "( )_| |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'K': line1 += " _   _ ";
               line2 += "( ) ( )";
               line3 += "| |/'/'";
               line4 += "| , <  ";
               line5 += "| |\\`\\ ";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
}
switch (str[i]) {
     case 'L': line1 += " _     ";
               line2 += "( )    ";
               line3 += "| |    ";
               line4 += "| |  _ ";
               line5 += "| |_( )";
               line6 += "(____/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'M': line1 += "       ";
               line2 += "/'\\_/`\\";
               line3 += "|     |";
               line4 += "| (_) |";
               line5 += "| | | |";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'N': line1 += " _   _ ";
               line2 += "( ) ( )";
               line3 += "| `\\| |";
               line4 += "| , ` |";
               line5 += "| |`\\ |";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'O': line1 += " _____ ";
               line2 += "(  _  )";
               line3 += "| ( ) |";
               line4 += "| | | |";
               line5 += "| (_) |";
               line6 += "(_____)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'P': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| |_) )";
               line4 += "| ,__/'";
               line5 += "| |    ";
               line6 += "(_)    ";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'Q': line1 += " _____ ";
               line2 += "(  _  )";
               line3 += "| ( ) |";
               line4 += "| | | |";
               line5 += "| (('\\|";
               line6 += "(___\\_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'R': line1 += " ___   ";
               line2 += "|  _`\\ ";
               line3 += "| (_) )";
               line4 += "| ,  / ";
               line5 += "| |\\ \\ ";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'S': line1 += " ___   ";
               line2 += "(  _`\\ ";
               line3 += "| (_(_)";
               line4 += "`\\__ \\ ";
               line5 += "( )_) |";
               line6 += "`\\____)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'T': line1 += " _____ ";
               line2 += "(_   _)";
               line3 += "  | |  ";
               line4 += "  | |  ";
               line5 += "  | |  ";
               line6 += "  (_)  ";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'U': line1 += " _   _ ";
               line2 += "( ) ( )";
               line3 += "| | | |";
               line4 += "| | | |";
               line5 += "| (_) |";
               line6 += "(_____)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'V': line1 += " _   _ ";
               line2 += "( ) ( )";
               line3 += "| | | |";
               line4 += "| | | |";
               line5 += "| \\_/ |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'W': line1 += " _       _ ";
               line2 += "( )  _  ( )";
               line3 += "| | ( ) | |";
               line4 += "| | | | | |";
               line5 += "| (_/ \\_) |";
               line6 += "`\\___x___/'";
               line7 += "           ";
               line8 += "           ";
               break;
     case 'X': line1 += " _    _ ";
               line2 += "( )  ( )";
               line3 += "`\\`\\/'/'";
               line4 += "  >  <  ";
               line5 += " /'/\\`\\ ";
               line6 += "(_)  (_)";
               line7 += "        ";
               line8 += "        ";
               break;
     case 'Y': line1 += " _     _ ";
               line2 += "( )   ( )";
               line3 += "`\\`\\_/'/'";
               line4 += "  `\\ /'  ";
               line5 += "   | |   ";
               line6 += "   (_)   ";
               line7 += "         ";
               line8 += "         ";
               break;
     case 'Z': line1 += " _______ ";
               line2 += "(_____  )";
               line3 += "     /'/'";
               line4 += "   /'/'_ ";
               line5 += " /'/'_( )";
               line6 += "(______/'";
               line7 += "         ";
               line8 += "         ";
               break;
     case '[': line1 += " ___ ";
               line2 += "(  _)";
               line3 += "| |  ";
               line4 += "| |  ";
               line5 += "| |_ ";
               line6 += "(___)";
               line7 += "     ";
               line8 += "     ";
               break;
     case '\\': line1 += " _          ";
               line2 += "( `\\        ";
               line3 += " `\\ `\\      ";
               line4 += "   `\\ `\\    ";
               line5 += "     `\\ `\\  ";
               line6 += "       `\\_) ";
               line7 += "            ";
               line8 += "            ";
               break;
     case ']': line1 += " ___ ";
               line2 += "(_  )";
               line3 += "  | |";
               line4 += "  | |";
               line5 += " _| |";
               line6 += "(___)";
               line7 += "     ";
               line8 += "     ";
               break;
     case '^': line1 += "  __  ";
               line2 += " /  \\ ";
               line3 += "(_/\\_)";
               line4 += "      ";
               line5 += "      ";
               line6 += "      ";
               line7 += "      ";
               line8 += "      ";
               break;
     case '_': line1 += "        ";
               line2 += "        ";
               line3 += "        ";
               line4 += "        ";
               line5 += "        ";
               line6 += "        ";
               line7 += " ______ ";
               line8 += "(______)";
               break;
     case '`': line1 += " _ ";
               line2 += "( )";
               line3 += " \\|";
               line4 += "   ";
               line5 += "   ";
               line6 += "   ";
               line7 += "   ";
               line8 += "   ";
               break;
     case 'a': line1 += "       ";
               line2 += "       ";
               line3 += "   _ _ ";
               line4 += " /'_` )";
               line5 += "( (_| |";
               line6 += "`\\__,_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'b': line1 += " _     ";
               line2 += "( )    ";
               line3 += "| |_   ";
               line4 += "| '_`\\ ";
               line5 += "| |_) )";
               line6 += "(_,__/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'c': line1 += "       ";
               line2 += "       ";
               line3 += "   ___ ";
               line4 += " /'___)";
               line5 += "( (___ ";
               line6 += "`\\____)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'd': line1 += "     _ ";
               line2 += "    ( )";
               line3 += "   _| |";
               line4 += " /'_` |";
               line5 += "( (_| |";
               line6 += "`\\__,_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'e': line1 += "       ";
               line2 += "       ";
               line3 += "   __  ";
               line4 += " /'__`\\";
               line5 += "(  ___/";
               line6 += "`\\____)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'f': line1 += "       ";
               line2 += "       ";
               line3 += "   ___ ";
               line4 += " /'___)";
               line5 += "| (__  ";
               line6 += "| ,__) ";
               line7 += "| |    ";
               line8 += "(_)    ";
               break;
     case 'g': line1 += "       ";
               line2 += "       ";
               line3 += "   __  ";
               line4 += " /'_ `\\";
               line5 += "( (_) |";
               line6 += "`\\__  |";
               line7 += "( )_) |";
               line8 += " \\___/'";
               break;
     case 'h': line1 += " _     ";
               line2 += "( )    ";
               line3 += "| |__  ";
               line4 += "|  _ `\\";
               line5 += "| | | |";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'i': line1 += "   ";
               line2 += " _ ";
               line3 += "(_)";
               line4 += "| |";
               line5 += "| |";
               line6 += "(_)";
               line7 += "   ";
               line8 += "   ";
               break;
     case 'j': line1 += "       ";
               line2 += "     _ ";
               line3 += "    (_)";
               line4 += "    | |";
               line5 += "    | |";
               line6 += " _  | |";
               line7 += "( )_| |";
               line8 += "`\\___/'";
               break;
     case 'k': line1 += " _     ";
               line2 += "( )    ";
               line3 += "| |/') ";
               line4 += "| , <  ";
               line5 += "| |\\`\\ ";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'l': line1 += " _   ";
               line2 += "(_ ) ";
               line3 += " | | ";
               line4 += " | | ";
               line5 += " | | ";
               line6 += "(___)";
               line7 += "     ";
               line8 += "     ";
               break;
     case 'm': line1 += "           ";
               line2 += "           ";
               line3 += "  ___ ___  ";
               line4 += "/' _ ` _ `\\";
               line5 += "| ( ) ( ) |";
               line6 += "(_) (_) (_)";
               line7 += "           ";
               line8 += "           ";
               break;
     case 'n': line1 += "       ";
               line2 += "       ";
               line3 += "  ___  ";
               line4 += "/' _ `\\";
               line5 += "| ( ) |";
               line6 += "(_) (_)";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'o': line1 += "       ";
               line2 += "       ";
               line3 += "   _   ";
               line4 += " /'_`\\ ";
               line5 += "( (_) )";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'p': line1 += "       ";
               line2 += "       ";
               line3 += " _ _   ";
               line4 += "( '_`\\ ";
               line5 += "| (_) )";
               line6 += "| ,__/'";
               line7 += "| |    ";
               line8 += "(_)    ";
               break;
     case 'q': line1 += "       ";
               line2 += "       ";
               line3 += "   _ _ ";
               line4 += " /'_` )";
               line5 += "( (_) |";
               line6 += "`\\__, |";
               line7 += "    | |";
               line8 += "    (_)";
               break;
     case 'r': line1 += "      ";
               line2 += "      ";
               line3 += " _ __ ";
               line4 += "( '__)";
               line5 += "| |   ";
               line6 += "(_)   ";
               line7 += "      ";
               line8 += "      ";
               break;
     case 's': line1 += "      ";
               line2 += "      ";
               line3 += "  ___ ";
               line4 += "/',__)";
               line5 += "\\__, \\";
               line6 += "(____/";
               line7 += "      ";
               line8 += "      ";
               break;
     case 't': line1 += " _   ";
               line2 += "( )_ ";
               line3 += "| ,_)";
               line4 += "| |  ";
               line5 += "| |_ ";
               line6 += "`\\__)";
               line7 += "     ";
               line8 += "     ";
               break;
     case 'u': line1 += "       ";
               line2 += "       ";
               line3 += " _   _ ";
               line4 += "( ) ( )";
               line5 += "| (_) |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'v': line1 += "       ";
               line2 += "       ";
               line3 += " _   _ ";
               line4 += "( ) ( )";
               line5 += "| \\_/ |";
               line6 += "`\\___/'";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'w': line1 += "           ";
               line2 += "           ";
               line3 += " _   _   _ ";
               line4 += "( ) ( ) ( )";
               line5 += "| \\_/ \\_/ |";
               line6 += "`\\___x___/'";
               line7 += "           ";
               line8 += "           ";
               break;
     case 'x': line1 += "       ";
               line2 += "       ";
               line3 += "       ";
               line4 += "(`\\/') ";
               line5 += " >  <  ";
               line6 += "(_/\\_) ";
               line7 += "       ";
               line8 += "       ";
               break;
     case 'y': line1 += "       ";
               line2 += "       ";
               line3 += " _   _ ";
               line4 += "( ) ( )";
               line5 += "| (_) |";
               line6 += "`\\__, |";
               line7 += "( )_| |";
               line8 += "`\\___/'";
               break;
     case 'z': line1 += "       ";
               line2 += "       ";
               line3 += " ____  ";
               line4 += "(_  ,) ";
               line5 += " /'/_  ";
               line6 += "(____) ";
               line7 += "       ";
               line8 += "       ";
               break;
     case '{': line1 += "    _ ";
               line2 += "  /' )";
               line3 += " | ,/'";
               line4 += "<' |  ";
               line5 += " | `\\ ";
               line6 += " `\\__)";
               line7 += "      ";
               line8 += "      ";
               break;
     case '|': line1 += "   ";
               line2 += " _ ";
               line3 += "( )";
               line4 += "| |";
               line5 += "| |";
               line6 += "| |";
               line7 += "(_)";
               line8 += "   ";
               break;
     case '}': line1 += " _    ";
               line2 += "( `\\  ";
               line3 += "`\\  | ";
               line4 += "  | `>";
               line5 += " /' | ";
               line6 += "(__/' ";
               line7 += "      ";
               line8 += "      ";
               break;
     case '~': line1 += "   _   _ ";
               line2 += " /' \\/' )";
               line3 += "(_/\\__/' ";
               line4 += "         ";
               line5 += "         ";
               line6 += "         ";
               line7 += "         ";
               line8 += "         ";
               break;
     default:  break;
   }
 }
return line1+"\n"+line2+"\n"+line3+"\n"+line4+"\n"+
       line5+"\n"+line6+"\n"+line7+"\n"+line8+"\n";
}
