-------------------------------------------------------------------------------
 /* whisky*/
  ({ ({ 0,0,0 }), /* this is the pretitle field, 0 if on pretitle */
     ({ "the apprentice Wizard", "the apprentice Wizard",
	"the apprentice Wizard" }) }),					
 ({  ({ "Buddah","Buddah","Buddah"}),
     ({ "leader of the Monks", "leader of the Monks",
	"master of the 8th level" }) }),					
  ({ ({ "Monkmaster","Monkmastress","Monkmaster"})
     ({ "ruler of a province", "ruler of a province",
	"ruler of a province" }) }),			
  ({ ({ "Monkmaster","Monkmastress","Monkmaster" }),
     ({ "representative of the province", "representative of the province",
	"representative of the province" }) }),			
  ({ ({ "Major Monk","Major Nun","Major Monk" }),
     ({ "guardian master of the province", "guardian mastress of the province",
        "guardian master of the province" }) }),			
  ({ ({ "Major Monk","Major Nun","Major Monk" }),
     ({ "master of psychokinesis", "mastress of psychokinesis",
        "master of psychokinesis"}) }),			
  ({ ({ "Higher Monk","Higher Nun","Higher Monk" }),
     ({ "master of spiritualism", "mastress of spiritualism",
	"master of spiritualism" }) }),			
  ({ ({ "Higher Monk","Higher Nun","Higher Monk" }),
     ({ "ringleader of the province", "ringleader of the province",
	"ringleader of the province" }) }),			
  ({ ({ "Older Monk","Older Nun","Older Monk" }),
     ({ "master of concentration", "mastress of concentration",
	"master of concentration" }) }),		
  ({ ({ "Older Monk","Older Nun","Older Monk" }),
     ({ "judge of man","judge of man",
	"judge of man" }) }),					
  ({ ({ "Monk","Nun","Monk" }),
     ({ "respectful expert of imagination ", "respectful expert of imagination",
        "respectful expert of imagination" }) }),						
  ({ ({ "Monk","Nun","Monk" }),
     ({ "respectful expert of temptation", "respectful expert of temptation",
	"respectful expert of temptation" }) }),					
  ({ ({ "Minor Monk","Minor Nun","Minor Monk" }),
     ({ "expert of sacrifice", "expert of sacrifice",
	"expert of sacrifice" }) }),				
  ({ ({ "Minor Monk","Minor Nun","Minor Monk" }),
     ({ "expert of satisfaction","expert of satisfaction",
	"expert of satisfaction" }) }),						
  ({ ({ "Lower Monk","Lower Nun","Lower Monk" }),
     ({ "teacher of elements", "teacher of elements",
        "student of elements" }) }),						
  ({ ({ "Lower Monk","Lower Nun","Lower Monk" }),
     ({ "teacher of religion", "teacher of religion",
 	"teacher of religion" }) }),					
  ({ ({ "Lower Monk","Lower Nun","Lower Monk" }),
     ({ "teacher of concentration","teacher of concentration",
	"teacher of concentration" }) }),					
  ({ ({ "Lower Monk","Lower Nun","Lower Monk" }),
     ({ "teacher of law","teacher of law",
        "teacher of law" }) }),			
  ({ ({ "Utter Monk","Utter Nun","Utter Monk" }),
     ({ "follower of Buddah","follower of Buddah",
	"follower of Buddah" }) }),					
  ({ ({ "Utter Monk","Utter Nun","Utter Monk" }),
     ({ "administrator of the province","administrator of the province", 
        "administrator of the province" }) }),				
  ({ ({ "Utter Monk","Utter Nun","Utter Monk" }), 
     ({ "beholder of religion","beholder of religion",
        "beholder of religion" }) }),						
  ({ ({ "Utter Monk","Utter Nun","Utter Monk " }),
     ({ "beholder of humans","beholder of humans",
        "beholder of humans" }) }),						
  ({ ({ "Utter Monk","Utter Nun","Utter Monk" }),
     ({ "beholder of law","beholder of law",
      	"beholder of law" }) }),					
  ({ ({ "Apprentice Monk","Apprentice Nun","Apprentice Monk" }),
     ({ "student of religion","student of religion",
     	"student of religion" }),						
  ({ ({ "Apprentice Monk","Apprentice Nun","Apprentice Monk" }),
     ({ "student of concentration","student of concentration",
	"student of concentration" }),						
  ({ ({ "Apprentice Monk","Apprentice Nun","Apprentice Monk" }),
     ({ "student of law,"student of law",
 	"student of law" }),							
  ({ ({ 0,0,0 }),
     ({ "the hopeful straggler","the hopeful straggless",
	"the hopeful straggler" }),
  ({ ({ 0,0,0 }),
     ({ "the hopeful satisfier","the hopeful satisfier",
	"the hopeful satisfier" }),						
  ({ ({ 0,0,0 }),
     ({ "the wondering stool pigeon","the wondering stool pigeoness",
        "the wondering stool pigeon" }),				
  ({ ({ 0,0,0 }),
     ({ "the begging rag picker","the begging rag pickess",
     	"the begging rag picker" }),						
 });
-------------------------------------------------------------------------------
