#!/bin/csh -f
#
# @(#) hop  By Hans van der Linden
#
foreach col ( 0 1 2 3 4 5 6 )
foreach row ( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 )
set filename=.c
set filename=_$row$filename
set filename=t_$col$filename
echo $filename
cat template | sed "/X, Y/s//$col, $row/" > $filename
end
end

