#!/bin/csh -f
#
# @(#) hop  By Hans van der Linden
#
set prevrow=-1
foreach row ( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 )
set filename=.c
set filename=$row$filename
set filename=wp_$filename
echo $filename
cat wptemplate | sed "/Y/s//$prevrow/" > $filename
set prevrow=$row
end

