#define TP this_player()
#define TPN  TP->query_name()
#define TPRN TP->query_real_name()
#define SM "spells/master"
#define SKM "obj/skill_master"
#define QR "room/quest_room"
#define E    environment
#define U    u[i]
#define GM   "guild/master"
#define CR   "\n"
#define BS   92
#define LB   '['
#define RB   ']'
#define GL globals
#define a globals[0]
#define b globals[1]
#define c globals[2]
#define d globals[3]
#define e globals[4]
#define f globals[5]
#define g globals[6]
#define h globals[7]
#define i globals[8]
#define j globals[9]
#define k globals[10]
#define l globals[11]
#define m globals[12]
#define n globals[13]
#define o globals[14]
#define p globals[15]
#define q globals[16]
#define r globals[17]
#define s globals[18]
#define t globals[19]
#define u globals[20]
#define v globals[21]
#define w globals[22]
#define x globals[23]
#define y globals[24]
#define z globals[25]
